-- Saber Cristao - V1 Seed Questions (pt-BR)
-- Run this after v1_initial_schema.sql

insert into public.questions (
  language,
  category,
  difficulty,
  level,
  question_text,
  option_a,
  option_b,
  option_c,
  option_d,
  correct_option,
  explanation,
  bible_reference,
  doctrine_tag,
  review_status,
  is_active
)
values
(
  'pt-BR',
  'Antigo Testamento',
  1,
  1,
  'Quem construiu a arca por ordem de Deus?',
  'Abraão',
  'Noé',
  'Moisés',
  'Davi',
  'B',
  'Noé construiu a arca em obediência a Deus diante do juízo do dilúvio.',
  'Gênesis 6:14',
  'Obediência',
  'approved',
  true
),
(
  'pt-BR',
  'Novo Testamento',
  1,
  1,
  'Qual evangelho começa com: "No princípio era o Verbo"?',
  'Mateus',
  'Marcos',
  'Lucas',
  'João',
  'D',
  'O prólogo de João destaca Cristo como o Verbo eterno de Deus.',
  'João 1:1',
  'Cristologia',
  'approved',
  true
),
(
  'pt-BR',
  'Evangelhos',
  1,
  1,
  'Quem batizou Jesus no rio Jordão?',
  'Pedro',
  'João Batista',
  'Tiago',
  'André',
  'B',
  'João Batista foi o profeta que preparou o caminho do Senhor.',
  'Mateus 3:13-17',
  'Batismo',
  'approved',
  true
),
(
  'pt-BR',
  'Antigo Testamento',
  2,
  2,
  'Qual foi o líder usado por Deus para tirar Israel do Egito?',
  'Josué',
  'Samuel',
  'Moisés',
  'Salomão',
  'C',
  'Deus levantou Moisés para conduzir o povo na libertação do Egito.',
  'Êxodo 3:10',
  'Redenção',
  'approved',
  true
),
(
  'pt-BR',
  'Doutrina Cristã',
  2,
  2,
  'Segundo Efésios 2:8-9, a salvação é recebida por:',
  'Mérito pessoal',
  'Obras da lei',
  'Graça, mediante a fé',
  'Tradição humana',
  'C',
  'A salvação é dom de Deus, não resultado de obras humanas.',
  'Efésios 2:8-9',
  'Sola Gratia',
  'approved',
  true
),
(
  'pt-BR',
  'Reforma Protestante',
  2,
  3,
  'Qual das opções é uma das Cinco Solas da Reforma?',
  'Sola Caritas',
  'Sola Scriptura',
  'Sola Ecclesia',
  'Sola Cultura',
  'B',
  'Sola Scriptura afirma a Escritura como autoridade suprema para fé e prática.',
  '2 Timóteo 3:16-17',
  'Sola Scriptura',
  'approved',
  true
),
(
  'pt-BR',
  'Novo Testamento',
  2,
  3,
  'Quantos livros há no Novo Testamento?',
  '39',
  '27',
  '66',
  '12',
  'B',
  'O Novo Testamento é composto por 27 livros.',
  'Cânon Bíblico',
  'Cânon',
  'approved',
  true
),
(
  'pt-BR',
  'Antigo Testamento',
  3,
  4,
  'Qual rei escreveu grande parte de Provérbios?',
  'Saul',
  'Ezequias',
  'Salomão',
  'Josias',
  'C',
  'Salomão recebeu sabedoria de Deus e escreveu provérbios.',
  'Provérbios 1:1',
  'Sabedoria',
  'approved',
  true
),
(
  'pt-BR',
  'Doutrina Cristã',
  3,
  4,
  'A doutrina da justificação ensina que somos declarados justos por Deus com base em:',
  'Nossas obras',
  'Rituais religiosos',
  'Justiça de Cristo recebida pela fé',
  'Boas intenções',
  'C',
  'A justificação é ato forense de Deus com base na obra de Cristo, recebida pela fé.',
  'Romanos 3:24-26',
  'Justificação',
  'approved',
  true
),
(
  'pt-BR',
  'Evangelhos',
  3,
  5,
  'Qual discípulo negou Jesus três vezes antes do cantar do galo?',
  'Tomé',
  'Pedro',
  'Filipe',
  'Mateus',
  'B',
  'Pedro negou Jesus, mas depois foi restaurado pelo Senhor.',
  'Lucas 22:61-62',
  'Arrependimento',
  'approved',
  true
);

